-- 01_setup.sql: Database, schema, and warehouse setup
CREATE DATABASE IF NOT EXISTS CLINICAL_COPILOT;
CREATE SCHEMA IF NOT EXISTS CLINICAL_COPILOT.CORE;

CREATE WAREHOUSE IF NOT EXISTS COPILOT_WH
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE DATABASE CLINICAL_COPILOT;
USE SCHEMA CORE;
USE WAREHOUSE COPILOT_WH;
