-- =============================================================================
-- SnowCare360 RBAC & Security Setup
-- Database: CLINICAL_COPILOT | Schema: CORE
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CLINICAL_COPILOT;
USE SCHEMA CORE;
USE WAREHOUSE COPILOT_WH;

-- =============================================================================
-- 1A. FUNCTIONAL ROLES
-- =============================================================================

CREATE ROLE IF NOT EXISTS SNOWCARE_MEMBER_READ;
CREATE ROLE IF NOT EXISTS SNOWCARE_CLINICAL_READ;
CREATE ROLE IF NOT EXISTS SNOWCARE_CLAIMS_READ;
CREATE ROLE IF NOT EXISTS SNOWCARE_DOCUMENT_READ;
CREATE ROLE IF NOT EXISTS SNOWCARE_DOCUMENT_UPLOAD;
CREATE ROLE IF NOT EXISTS SNOWCARE_POLICY_READ;
CREATE ROLE IF NOT EXISTS SNOWCARE_AUDIT_READ;
CREATE ROLE IF NOT EXISTS SNOWCARE_JOB_READ;
CREATE ROLE IF NOT EXISTS SNOWCARE_MEMBER_WRITE;

-- =============================================================================
-- 1B. PERSONA ROLES
-- =============================================================================

CREATE ROLE IF NOT EXISTS SNOWCARE_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS CARE_MANAGER_ROLE;
CREATE ROLE IF NOT EXISTS COMPLIANCE_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS OPERATIONS_ANALYST_ROLE;

-- =============================================================================
-- 1C. ROLE HIERARCHY
-- =============================================================================

-- SNOWCARE_ADMIN_ROLE inherits ALL functional roles
GRANT ROLE SNOWCARE_MEMBER_READ     TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE SNOWCARE_CLINICAL_READ   TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE SNOWCARE_CLAIMS_READ     TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE SNOWCARE_DOCUMENT_READ   TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE SNOWCARE_DOCUMENT_UPLOAD TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE SNOWCARE_POLICY_READ     TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE SNOWCARE_AUDIT_READ      TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE SNOWCARE_JOB_READ        TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE SNOWCARE_MEMBER_WRITE    TO ROLE SNOWCARE_ADMIN_ROLE;

-- CARE_MANAGER_ROLE
GRANT ROLE SNOWCARE_MEMBER_READ     TO ROLE CARE_MANAGER_ROLE;
GRANT ROLE SNOWCARE_CLINICAL_READ   TO ROLE CARE_MANAGER_ROLE;
GRANT ROLE SNOWCARE_DOCUMENT_READ   TO ROLE CARE_MANAGER_ROLE;
GRANT ROLE SNOWCARE_DOCUMENT_UPLOAD TO ROLE CARE_MANAGER_ROLE;
GRANT ROLE SNOWCARE_MEMBER_WRITE    TO ROLE CARE_MANAGER_ROLE;

-- COMPLIANCE_ANALYST_ROLE
GRANT ROLE SNOWCARE_MEMBER_READ     TO ROLE COMPLIANCE_ANALYST_ROLE;
GRANT ROLE SNOWCARE_CLINICAL_READ   TO ROLE COMPLIANCE_ANALYST_ROLE;
GRANT ROLE SNOWCARE_CLAIMS_READ     TO ROLE COMPLIANCE_ANALYST_ROLE;
GRANT ROLE SNOWCARE_POLICY_READ     TO ROLE COMPLIANCE_ANALYST_ROLE;
GRANT ROLE SNOWCARE_DOCUMENT_READ   TO ROLE COMPLIANCE_ANALYST_ROLE;
GRANT ROLE SNOWCARE_AUDIT_READ      TO ROLE COMPLIANCE_ANALYST_ROLE;

-- OPERATIONS_ANALYST_ROLE
GRANT ROLE SNOWCARE_MEMBER_READ     TO ROLE OPERATIONS_ANALYST_ROLE;
GRANT ROLE SNOWCARE_CLAIMS_READ     TO ROLE OPERATIONS_ANALYST_ROLE;
GRANT ROLE SNOWCARE_JOB_READ        TO ROLE OPERATIONS_ANALYST_ROLE;

-- All persona roles roll up to SNOWCARE_ADMIN_ROLE
GRANT ROLE CARE_MANAGER_ROLE        TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE COMPLIANCE_ANALYST_ROLE  TO ROLE SNOWCARE_ADMIN_ROLE;
GRANT ROLE OPERATIONS_ANALYST_ROLE  TO ROLE SNOWCARE_ADMIN_ROLE;

-- SNOWCARE_ADMIN_ROLE rolls up to ACCOUNTADMIN
GRANT ROLE SNOWCARE_ADMIN_ROLE TO ROLE ACCOUNTADMIN;

-- =============================================================================
-- 1D. DATABASE / SCHEMA / WAREHOUSE GRANTS
-- =============================================================================

GRANT USAGE ON DATABASE CLINICAL_COPILOT       TO ROLE SNOWCARE_MEMBER_READ;
GRANT USAGE ON SCHEMA CLINICAL_COPILOT.CORE    TO ROLE SNOWCARE_MEMBER_READ;
GRANT USAGE ON WAREHOUSE COPILOT_WH            TO ROLE SNOWCARE_MEMBER_READ;

-- =============================================================================
-- 1E. TABLE-LEVEL GRANTS PER FUNCTIONAL ROLE
-- =============================================================================

-- SNOWCARE_MEMBER_READ
GRANT SELECT ON TABLE MEMBER              TO ROLE SNOWCARE_MEMBER_READ;
GRANT SELECT ON TABLE ENCOUNTER           TO ROLE SNOWCARE_MEMBER_READ;
GRANT SELECT ON TABLE DIAGNOSIS           TO ROLE SNOWCARE_MEMBER_READ;
GRANT SELECT ON TABLE MEDICATION          TO ROLE SNOWCARE_MEMBER_READ;
GRANT SELECT ON TABLE LAB_RESULT          TO ROLE SNOWCARE_MEMBER_READ;
GRANT SELECT ON TABLE MEMBER_360_SUMMARY  TO ROLE SNOWCARE_MEMBER_READ;
GRANT SELECT ON TABLE RISK_DELTA_LOG      TO ROLE SNOWCARE_MEMBER_READ;

-- SNOWCARE_CLINICAL_READ
GRANT SELECT ON TABLE CLINICAL_NOTE               TO ROLE SNOWCARE_CLINICAL_READ;
GRANT SELECT ON TABLE DRUG_INTERACTION_GUIDELINE   TO ROLE SNOWCARE_CLINICAL_READ;
GRANT SELECT ON TABLE ATTACHMENT                   TO ROLE SNOWCARE_CLINICAL_READ;

-- SNOWCARE_DOCUMENT_READ
GRANT SELECT ON TABLE DOCUMENT          TO ROLE SNOWCARE_DOCUMENT_READ;
GRANT SELECT ON TABLE DOCUMENT_CHUNK    TO ROLE SNOWCARE_DOCUMENT_READ;
GRANT SELECT ON TABLE POLICY_DOCUMENT   TO ROLE SNOWCARE_DOCUMENT_READ;

-- SNOWCARE_DOCUMENT_UPLOAD
GRANT INSERT ON TABLE DOCUMENT        TO ROLE SNOWCARE_DOCUMENT_UPLOAD;
GRANT INSERT ON TABLE DOCUMENT_CHUNK  TO ROLE SNOWCARE_DOCUMENT_UPLOAD;

-- SNOWCARE_CLAIMS_READ
GRANT SELECT ON TABLE CLAIM TO ROLE SNOWCARE_CLAIMS_READ;

-- SNOWCARE_AUDIT_READ
GRANT SELECT ON TABLE AI_AUDIT_LOG TO ROLE SNOWCARE_AUDIT_READ;
GRANT INSERT ON TABLE AI_AUDIT_LOG TO ROLE SNOWCARE_AUDIT_READ;

-- SNOWCARE_MEMBER_WRITE
GRANT INSERT, UPDATE ON TABLE MEMBER        TO ROLE SNOWCARE_MEMBER_WRITE;
GRANT INSERT, UPDATE ON TABLE ENCOUNTER     TO ROLE SNOWCARE_MEMBER_WRITE;
GRANT INSERT, UPDATE ON TABLE MEDICATION    TO ROLE SNOWCARE_MEMBER_WRITE;
GRANT INSERT, UPDATE ON TABLE DIAGNOSIS     TO ROLE SNOWCARE_MEMBER_WRITE;
GRANT INSERT, UPDATE ON TABLE LAB_RESULT    TO ROLE SNOWCARE_MEMBER_WRITE;
GRANT INSERT, UPDATE ON TABLE CLINICAL_NOTE TO ROLE SNOWCARE_MEMBER_WRITE;
GRANT INSERT, UPDATE ON TABLE CLAIM         TO ROLE SNOWCARE_MEMBER_WRITE;

-- SNOWCARE_ADMIN_ROLE direct grants
GRANT SELECT ON TABLE APP_USER TO ROLE SNOWCARE_ADMIN_ROLE;

-- =============================================================================
-- 1F. CORTEX / AGENT / UDF GRANTS
-- =============================================================================

-- Cortex Search Services
GRANT USAGE ON CORTEX SEARCH SERVICE CLINICAL_NOTES_SEARCH    TO ROLE SNOWCARE_CLINICAL_READ;
GRANT USAGE ON CORTEX SEARCH SERVICE DRUG_INTERACTION_SEARCH   TO ROLE SNOWCARE_CLINICAL_READ;
GRANT USAGE ON CORTEX SEARCH SERVICE POLICY_DOCS_SEARCH        TO ROLE SNOWCARE_CLINICAL_READ;
GRANT USAGE ON CORTEX SEARCH SERVICE DOCUMENT_SEARCH           TO ROLE SNOWCARE_CLINICAL_READ;

GRANT USAGE ON CORTEX SEARCH SERVICE CLINICAL_NOTES_SEARCH    TO ROLE SNOWCARE_DOCUMENT_READ;
GRANT USAGE ON CORTEX SEARCH SERVICE DRUG_INTERACTION_SEARCH   TO ROLE SNOWCARE_DOCUMENT_READ;
GRANT USAGE ON CORTEX SEARCH SERVICE POLICY_DOCS_SEARCH        TO ROLE SNOWCARE_DOCUMENT_READ;
GRANT USAGE ON CORTEX SEARCH SERVICE DOCUMENT_SEARCH           TO ROLE SNOWCARE_DOCUMENT_READ;

-- UDFs
GRANT USAGE ON FUNCTION SCORE_POLYPHARMACY_RISK(VARCHAR)          TO ROLE SNOWCARE_MEMBER_READ;
GRANT USAGE ON FUNCTION CHECK_POLICY_COMPLIANCE(VARCHAR, VARCHAR) TO ROLE SNOWCARE_CLINICAL_READ;

-- Semantic View
GRANT SELECT ON SEMANTIC VIEW CLINICAL_SEMANTIC_VIEW TO ROLE SNOWCARE_MEMBER_READ;

-- Agent (syntax may vary; documented for reference)
-- GRANT USAGE ON CORTEX AGENT CLINICAL_COPILOT_AGENT TO ROLE SNOWCARE_MEMBER_READ;

-- =============================================================================
-- 1G. USER-MEMBER ACCESS MAPPING TABLE
-- =============================================================================

CREATE OR REPLACE TABLE CLINICAL_COPILOT.CORE.USER_MEMBER_ACCESS (
    SNOWFLAKE_USER  VARCHAR NOT NULL,
    MEMBER_ID       VARCHAR NOT NULL,
    ACCESS_LEVEL    VARCHAR DEFAULT 'read',
    ASSIGNED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SNOWFLAKE_USER, MEMBER_ID)
);

-- Seed AMARGULAGANJI with access to all 50 members
INSERT INTO CLINICAL_COPILOT.CORE.USER_MEMBER_ACCESS (SNOWFLAKE_USER, MEMBER_ID)
SELECT 'AMARGULAGANJI', MEMBER_ID
FROM CLINICAL_COPILOT.CORE.MEMBER;

-- =============================================================================
-- 1H. ROW ACCESS POLICY ON MEMBER_ID
-- =============================================================================

CREATE OR REPLACE ROW ACCESS POLICY MEMBER_ACCESS_POLICY
  AS (member_id_val VARCHAR) RETURNS BOOLEAN ->
    IS_ROLE_IN_SESSION('SNOWCARE_ADMIN_ROLE')
    OR IS_ROLE_IN_SESSION('ACCOUNTADMIN')
    OR EXISTS (
      SELECT 1 FROM CLINICAL_COPILOT.CORE.USER_MEMBER_ACCESS
      WHERE SNOWFLAKE_USER = CURRENT_USER()
        AND MEMBER_ID = member_id_val
    );

-- Apply to all tables with MEMBER_ID
ALTER TABLE MEMBER              ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE ENCOUNTER           ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE MEDICATION          ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE DIAGNOSIS           ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE LAB_RESULT          ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE CLINICAL_NOTE       ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE CLAIM               ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE DOCUMENT            ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE RISK_DELTA_LOG      ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE AI_AUDIT_LOG        ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE ATTACHMENT          ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);
ALTER TABLE MEMBER_360_SUMMARY  ADD ROW ACCESS POLICY MEMBER_ACCESS_POLICY ON (MEMBER_ID);

-- =============================================================================
-- 1I. MASKING POLICIES
-- =============================================================================

-- PCP_NAME masking
CREATE OR REPLACE MASKING POLICY PCP_NAME_MASK AS (val VARCHAR) RETURNS VARCHAR ->
  CASE
    WHEN IS_ROLE_IN_SESSION('CARE_MANAGER_ROLE')       THEN val
    WHEN IS_ROLE_IN_SESSION('COMPLIANCE_ANALYST_ROLE')  THEN val
    WHEN IS_ROLE_IN_SESSION('SNOWCARE_ADMIN_ROLE')      THEN val
    WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN')              THEN val
    ELSE '***REDACTED***'
  END;

ALTER TABLE MEMBER MODIFY COLUMN PCP_NAME SET MASKING POLICY PCP_NAME_MASK;

-- DOB masking (MEMBER.DOB exists as DATE)
CREATE OR REPLACE MASKING POLICY DOB_MASK AS (val DATE) RETURNS DATE ->
  CASE
    WHEN IS_ROLE_IN_SESSION('CARE_MANAGER_ROLE')       THEN val
    WHEN IS_ROLE_IN_SESSION('COMPLIANCE_ANALYST_ROLE')  THEN val
    WHEN IS_ROLE_IN_SESSION('SNOWCARE_ADMIN_ROLE')      THEN val
    WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN')              THEN val
    ELSE DATE_FROM_PARTS(YEAR(val), 1, 1)  -- mask to Jan 1 of birth year
  END;

ALTER TABLE MEMBER MODIFY COLUMN DOB SET MASKING POLICY DOB_MASK;

-- =============================================================================
-- 1J. GRANT CALLER PRIVILEGES (for executeAsCaller)
-- =============================================================================

GRANT CALLER USAGE ON DATABASE CLINICAL_COPILOT        TO ROLE ACCOUNTADMIN;
GRANT CALLER USAGE ON SCHEMA CLINICAL_COPILOT.CORE     TO ROLE ACCOUNTADMIN;
GRANT CALLER USAGE ON WAREHOUSE COPILOT_WH             TO ROLE ACCOUNTADMIN;

-- GRANT CALLER SELECT on each table
GRANT CALLER SELECT ON TABLE MEMBER                     TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE ENCOUNTER                  TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE DIAGNOSIS                  TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE MEDICATION                 TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE LAB_RESULT                 TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE CLINICAL_NOTE              TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE CLAIM                      TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE DOCUMENT                   TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE DOCUMENT_CHUNK             TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE POLICY_DOCUMENT            TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE DRUG_INTERACTION_GUIDELINE TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE ATTACHMENT                 TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE MEMBER_360_SUMMARY         TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE RISK_DELTA_LOG             TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE AI_AUDIT_LOG               TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE APP_USER                   TO ROLE ACCOUNTADMIN;
GRANT CALLER SELECT ON TABLE USER_MEMBER_ACCESS         TO ROLE ACCOUNTADMIN;

-- GRANT CALLER INSERT on writable tables
GRANT CALLER INSERT ON TABLE AI_AUDIT_LOG               TO ROLE ACCOUNTADMIN;
GRANT CALLER INSERT ON TABLE DOCUMENT                   TO ROLE ACCOUNTADMIN;
GRANT CALLER INSERT ON TABLE DOCUMENT_CHUNK             TO ROLE ACCOUNTADMIN;
GRANT CALLER INSERT ON TABLE MEMBER                     TO ROLE ACCOUNTADMIN;
GRANT CALLER INSERT ON TABLE ENCOUNTER                  TO ROLE ACCOUNTADMIN;
GRANT CALLER INSERT ON TABLE MEDICATION                 TO ROLE ACCOUNTADMIN;
GRANT CALLER INSERT ON TABLE DIAGNOSIS                  TO ROLE ACCOUNTADMIN;
GRANT CALLER INSERT ON TABLE LAB_RESULT                 TO ROLE ACCOUNTADMIN;
GRANT CALLER INSERT ON TABLE CLINICAL_NOTE              TO ROLE ACCOUNTADMIN;
GRANT CALLER INSERT ON TABLE CLAIM                      TO ROLE ACCOUNTADMIN;

-- GRANT CALLER UPDATE on writable tables
GRANT CALLER UPDATE ON TABLE MEMBER                     TO ROLE ACCOUNTADMIN;
GRANT CALLER UPDATE ON TABLE ENCOUNTER                  TO ROLE ACCOUNTADMIN;
GRANT CALLER UPDATE ON TABLE MEDICATION                 TO ROLE ACCOUNTADMIN;
GRANT CALLER UPDATE ON TABLE DIAGNOSIS                  TO ROLE ACCOUNTADMIN;
GRANT CALLER UPDATE ON TABLE LAB_RESULT                 TO ROLE ACCOUNTADMIN;
GRANT CALLER UPDATE ON TABLE CLINICAL_NOTE              TO ROLE ACCOUNTADMIN;
GRANT CALLER UPDATE ON TABLE CLAIM                      TO ROLE ACCOUNTADMIN;

-- =============================================================================
-- 1K. ACCOUNT & USER SETTINGS
-- =============================================================================

ALTER ACCOUNT SET SERVICE_CALLER_TOKEN_VALIDITY_SECS = 3600;
ALTER USER AMARGULAGANJI SET DEFAULT_SECONDARY_ROLES = ('ALL');

-- =============================================================================
-- END OF RBAC SETUP
-- =============================================================================
